name = "extracker"
compatibility_date = "2023-08-23"

workers_dev = true
type = "webpack"

node_compat = true

[vars]
KINDE_DOMAIN = 'https://trackexpense.kinde.com'
KINDE_REDIRECT_URI = 'https://extracker.shebl.workers.dev/api/callback'
KINDE_LOGOUT_REDIRECT_URI = 'https://extracker.shebl.workers.dev'



[site]
bucket = "./front-end/dist"
entry-point = "workers-site"

[build]
command = "npm run build && node generate-manifest.js"

# Do not include sensitive information here
# Use `wrangler secret put` for sensitive data
# KINDE_CLIENT_ID
# KINDE_CLIENT_SECRET
# DRIZZLE_DATABASE_URL